"""
ui/backend/main.py — FastAPI backend for the escalation review UI and KB chat.

Endpoints:
  GET  /api/health
  GET  /api/escalations
  POST /api/escalations/{thread_id}/decide
  POST /api/chat/stream   ← SSE stream: create_react_agent + astream_events()

The pipeline service (pipeline.py --serve) polls for 'decided' rows and is
the sole process that resumes LangGraph pipelines — this backend never imports
the main pipeline graph or checkpointer directly.

Usage (run from agent-langgraph/ dir so store.py is importable):
    uvicorn ui.backend.main:app --port 8001 --reload
"""

import json
import sys
from contextlib import asynccontextmanager
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

# Allow imports from the agent-langgraph root (store.py, logger.py, …)
_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(_ROOT))

load_dotenv(_ROOT / ".env")

import store
from agents.kb_chat import get_chat_graph


@asynccontextmanager
async def lifespan(app: FastAPI):
    await store.get_pool()
    yield
    if store._pool:
        await store._pool.close()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ── helpers ───────────────────────────────────────────────────────────────────

def _serialize(row: dict) -> dict:
    """Convert asyncpg record fields to JSON-serialisable types."""
    return {k: (v.isoformat() if hasattr(v, "isoformat") else v) for k, v in row.items()}


# ── endpoints ─────────────────────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {"status": "ok"}


@app.get("/api/escalations")
async def list_escalations():
    """Return all escalations (pending + decided + resolved), newest first."""
    rows = await store.get_all_escalations()
    return [_serialize(r) for r in rows]


class DecisionRequest(BaseModel):
    decision: str  # "approve" | "override: <text>"


@app.post("/api/escalations/{thread_id}/decide")
async def decide(thread_id: str, body: DecisionRequest):
    """
    Record a human decision.

    Sets status='decided' in escalation_queue. The pipeline service
    (pipeline.py --serve) polls for 'decided' rows and resumes the graph.
    """
    decision = body.decision.strip()
    if not decision:
        raise HTTPException(status_code=400, detail="decision must not be empty")

    rows = await store.get_all_escalations()
    existing = next((r for r in rows if r["thread_id"] == thread_id), None)
    if existing is None:
        raise HTTPException(status_code=404, detail="Escalation not found")
    if existing["status"] != "pending":
        return {"status": "already_decided", "current_status": existing["status"]}

    await store.submit_decision(thread_id, decision)
    return {"status": "queued"}


# ── KB chat ───────────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    thread_id: str   # unique per conversation session (generated by frontend)
    message: str


@app.post("/api/chat/stream")
async def chat_stream(body: ChatRequest):
    """
    Stream a KB chat response using create_react_agent + astream_events().

    SSE protocol:
      data: {"type": "text",       "content": "..."}   — streamed token
      data: {"type": "tool_start", "tool": "..."}      — agent calling a tool
      data: {"type": "tool_end"}                       — tool call finished
      data: {"type": "done"}                           — stream complete
    """
    if not body.message.strip():
        raise HTTPException(status_code=400, detail="message must not be empty")

    graph = await get_chat_graph()
    config = {"configurable": {"thread_id": body.thread_id}}

    async def generate():
        try:
            async for event in graph.astream_events(
                {"messages": [{"role": "user", "content": body.message}]},
                config=config,
                version="v2",
            ):
                kind = event["event"]

                if kind == "on_chat_model_stream":
                    chunk = event["data"]["chunk"]
                    content = chunk.content if hasattr(chunk, "content") else ""
                    if isinstance(content, str) and content:
                        yield f"data: {json.dumps({'type': 'text', 'content': content})}\n\n"
                    elif isinstance(content, list):
                        for block in content:
                            if isinstance(block, dict) and block.get("type") == "text":
                                text = block.get("text", "")
                                if text:
                                    yield f"data: {json.dumps({'type': 'text', 'content': text})}\n\n"

                elif kind == "on_tool_start":
                    tool_name = event.get("name", "tool")
                    yield f"data: {json.dumps({'type': 'tool_start', 'tool': tool_name})}\n\n"

                elif kind == "on_tool_end":
                    yield f"data: {json.dumps({'type': 'tool_end'})}\n\n"

        except Exception as exc:
            yield f"data: {json.dumps({'type': 'error', 'content': str(exc)})}\n\n"

        yield f"data: {json.dumps({'type': 'done'})}\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
